# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amlogic/g16/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/amlogic/g16

PRODUCT_COPY_FILES += \
    vendor/amlogic/g16/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/amlogic/g16/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf
PRODUCT_COPY_FILES += \
    vendor/amlogic/g16/proprietary/vendor/etc/tvconfig/pq/pq.db:$(TARGET_COPY_OUT_VENDOR)/etc/tvconfig/pq/pq.db \
    vendor/amlogic/g16/proprietary/vendor/etc/tvconfig/pq/pq_default.ini:$(TARGET_COPY_OUT_VENDOR)/etc/tvconfig/pq/pq_default.ini \
    vendor/amlogic/g16/proprietary/vendor/lib/egl/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLES_mali.so \
    vendor/amlogic/g16/proprietary/vendor/lib/hw/gralloc.amlogic.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.amlogic.so \
    vendor/amlogic/g16/proprietary/vendor/lib/hw/hwcomposer.amlogic.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hwcomposer.amlogic.so
